const GET_SUPPORTED_EXCHANGES = 'GET_SUPPORTED_EXCHANGES';
const GET_SUPPORTED_EXCHANGES_SUCCESS = 'GET_SUPPORTED_EXCHANGES_SUCCESS';
const GET_SUPPORTED_EXCHANGES_FAIL = 'GET_SUPPORTED_EXCHANGES_FAIL';
const TOGGLE_EXCHANGE = 'TOGGLE_EXCHANGE'

export default {
  GET_SUPPORTED_EXCHANGES,
  GET_SUPPORTED_EXCHANGES_SUCCESS,
  GET_SUPPORTED_EXCHANGES_FAIL,
  TOGGLE_EXCHANGE,
}
